[package]
name = "morph_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer = "~0.15"
image = "~0.24"
polars = { version = "~0.35", features = ["lazy", "is_in", "interpolate", "search_sorted"] }
#nalgebra = { version = "~0.32", features = [] }
rfd = "~0.12"
